[project]
name = "ds-oc-projet4"
version = "0.1.0"
description = "Data Cleaning, analysis and Classification Model for ESN Turnover"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars==1.21.0",
    "pyarrow",
    "pandas==2.2.3",
    "numpy==1.26.4",
    "scikit-learn==1.8.0",
    "scipy==1.15.1",
    "matplotlib==3.10.0",
    "seaborn==0.13.2",
    "shap==0.50.0",
    "ipykernel==6.28.0",
    "imbalanced-learn==0.12.3",
    "phik==0.12.4"
    "fastapi==0.115.0",
    "uvicorn==0.30.6",
    "joblib==1.4.2",
    "pydantic==2.9.2"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"